name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Python tests
        run: python -m unittest app.scripts.tests

  javascript-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd ./chatbot/ && npm ci

      - name: Run Node.js tests
        run: cd ./chatbot/ && npm test
