name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -m unittest app.scripts.tests
